#!/bin/bash
ROOT=`dirname $0`
OS=`uname -s`
if [ "$OS" == "Darwin" ]; then
  export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$ROOT/node_modules/instantclient"
elif [ "$OS" == "Linux" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$ROOT/node_modules/instantclient"
else
  export PATH="$PATH:$ROOT/node_modules/instantclient"
fi
if [ -z "$*" ]; then
  export UV_THREADPOOL_SIZE=64
  $ROOT/node_modules/.bin/mocha -R spec --timeout 120000 --require $ROOT/test/init/init.js --reporter /home/biniam/jnksws/workspace/loopback-connector-oracle2/arch/s390x/os/sles-11/node_modules/build-framework/node_modules/mocha-jenkins-reporter
else
  echo "Running provided test command: $*"
  $*
fi

